// Generated by CoffeeScript 1.7.1
define(function() {
  return [
    {
      id: 12,
      views: [34, 43, 4],
      building: 5,
      floor: 2,
      unit_variants: [2, 4, 4]
    }, {
      id: 11,
      views: [4, 43, 4],
      building: 5,
      floor: 6,
      unit_variants: [2, 4]
    }
  ];
});
