// Generated by CoffeeScript 1.7.1
define(function() {
  return [
    {
      name: 'low',
      start: 0,
      end: 5
    }, {
      name: 'medium',
      start: 6,
      end: 10
    }, {
      name: 'high',
      start: 11,
      end: 15
    }
  ];
});
