// Generated by CoffeeScript 1.7.1
define(function() {
  return [
    {
      id: 1,
      name: "Available"
    }, {
      id: 2,
      name: "Sold"
    }, {
      id: 3,
      name: "Booked"
    }
  ];
});
