// Generated by CoffeeScript 1.7.1
define(function() {
  return [
    {
      id: 1,
      name: "UnitType1"
    }, {
      id: 2,
      name: "UnitType2"
    }, {
      id: 3,
      name: "UnitType3"
    }, {
      id: 4,
      name: "UnitType4"
    }, {
      id: 5,
      name: "UnitType5"
    }, {
      id: 6,
      name: "UnitType6"
    }, {
      id: 7,
      name: "UnitType7"
    }, {
      id: 8,
      name: "UnitType8"
    }, {
      id: 9,
      name: "UnitType9"
    }, {
      id: 10,
      name: "UnitType10"
    }, {
      id: 11,
      name: "UnitType11"
    }, {
      id: 12,
      name: "UnitType12"
    }, {
      id: 69,
      name: "UnitTType69"
    }
  ];
});
