// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['app', 'backbone'], function(App) {
  return App.module("Entities.UnitVariant", function(UnitVariant, App) {
    var API, UnitVariantCollection, unitVariantCollection;
    UnitVariant = (function(_super) {
      __extends(UnitVariant, _super);

      function UnitVariant() {
        return UnitVariant.__super__.constructor.apply(this, arguments);
      }

      UnitVariant.prototype.idAttribute = 'ID';

      UnitVariant.prototype.defaults = {
        name: '',
        carpetarea: '',
        sellablearea: ''
      };

      UnitVariant.prototype.name = 'unitVariant';

      return UnitVariant;

    })(Backbone.Model);
    UnitVariantCollection = (function(_super) {
      __extends(UnitVariantCollection, _super);

      function UnitVariantCollection() {
        return UnitVariantCollection.__super__.constructor.apply(this, arguments);
      }

      UnitVariantCollection.prototype.model = UnitVariant;

      UnitVariantCollection.prototype.url = function() {
        return AJAXURL;
      };

      return UnitVariantCollection;

    })(Backbone.Collection);
    unitVariantCollection = new UnitVariantCollection;
    API = {
      getUnitVariants: function() {
        var jsondata;
        jsondata = JSON.parse(UNITVARIANT);
        unitVariantCollection.add(jsondata);
        return unitVariantCollection;
      }
    };
    return App.reqres.setHandler("get:unitvariant:collection", function() {
      return API.getUnitVariants();
    });
  });
});
