// Generated by CoffeeScript 1.7.1
define('plugin-loader', [], function() {});

define('apps-loader', ['src/apps/footer/footer-controller', 'src/apps/header/header-controller', 'src/apps/screen-one/screen-one-controller'], function() {});

require(['spec/javascripts/fixtures/json/units', 'spec/javascripts/fixtures/json/views', 'spec/javascripts/fixtures/json/buildings', 'spec/javascripts/fixtures/json/unitvariants', 'spec/javascripts/fixtures/json/unittypes', 'plugin-loader', 'extm', 'apps-loader'], function(units, views, buildings, unitvariants, unittypes, plugins, Extm) {
  var staticApps;
  window.App = new Extm.Application;
  App.addRegions({
    headerRegion: '#header-region',
    footerRegion: '#footer-region',
    filterRegion: '#filter-region',
    mainRegion: '#main-region'
  });
  App.store.push('unit', units);
  App.store.push('view', views);
  App.store.push('building', buildings);
  App.store.push('unit_variant', unitvariants);
  App.store.push('unit_type', unittypes);
  staticApps = [['footer', App.footerRegion], ['header', App.headerRegion]];
  if (App.getCurrentRoute() === '') {
    staticApps.push(['screen:one', App.mainRegion]);
  }
  App.addStaticApps(staticApps);
  return App.start();
});
