// Generated by CoffeeScript 1.7.1
requirejs.config({
  urlArgs: "ver=" + (Math.random()),
  baseUrl: '../wp-content/themes/apartmentselector/spa',
  paths: {
    jquery: 'src/bower_components/jquery/dist/jquery',
    backbone: 'src/bower_components/backbone/backbone',
    underscore: 'src/bower_components/underscore/underscore',
    marionette: 'src/bower_components/marionette/lib/core/backbone.marionette',
    mustache: 'src/bower_components/mustache/mustache',
    text: 'src/bower_components/requirejs-text/text',
    backbonesyphon: 'src/bower_components/backbone.syphon/lib/amd/backbone.syphon',
    'backbone.wreqr': 'src/bower_components/backbone.wreqr/lib/backbone.wreqr',
    'backbone.babysitter': 'src/bower_components/backbone.babysitter/lib/backbone.babysitter',
    plupload: 'src/bower_components/plupload/js/plupload.full.min',
    jasmineajax: 'src/bower_components/jasmine-ajax/lib/mock-ajax',
    jasminejquery: 'src/bower_components/jasmine-jquery/lib/jasmine-jquery',
    jqueryvalidate: 'src/bower_components/jquery.validation/dist/jquery.validate',
    async: 'src/bower_components/async/lib/async',
    bootstraptour: 'src/bower_components/bootstrap-tour/build/js/bootstrap-tour.js',
    underscorestring: 'src/bower_components/underscore.string/lib/underscore.string',
    extm: 'src/bower_components/extm/lib/extm.amd',
    preload: 'src/bower_components/preload/jquery.preload'
  },
  shim: {
    jquery: ['underscore'],
    underscorestring: ['underscore'],
    backbone: ['jquery', 'underscore'],
    marionette: {
      deps: ['backbone', 'backbone.wreqr', 'backbone.babysitter']
    },
    backbonesyphon: ['backbone'],
    backboneassociations: ['backbone'],
    jqueryvalidate: ['jquery'],
    bootstrap: ['jquery'],
    bootstraptour: ['bootstrap'],
    jasminejquery: ['jquery'],
    jasmineajax: ['jquery'],
    plupload: {
      deps: ['jquery'],
      exports: 'plupload'
    },
    preload: ['jquery']
  }
});
