// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {
  var getRequireJSTasks;
  require('time-grunt')(grunt);
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    exec: {
      themeJS: {
        command: 'coffee -w -c -b ../js/'
      },
      spaJS: {
        command: 'coffee -w -c -b ../spa/'
      },
      compileall: {
        command: 'coffee -c -b ../../'
      }
    },
    lesslint: {
      options: {
        csslint: {
          "known-properties": false
        }
      },
      themeLess: {
        src: ["../css/*.less", "../css/**/*.less"]
      }
    },
    githooks: {
      all: {
        'pre-commit': 'themeJSOptimize'
      }
    },
    jshint: {
      options: {
        jshintrc: '.jshintrc',
        jshintignore: '.jshintignore',
        reporter: require('jshint-stylish')
      },
      themeJS: [],
      spaJS: []
    },
    coffeelint: {
      options: {
        configFile: 'coffeelint.json'
      },
      themeCoffee: {
        files: {
          src: ["../js/*.coffee", "../js/**/*.coffee"]
        }
      },
      spaCoffee: {
        files: {
          src: ["../spa/*.coffee", "../spa/**/*.coffee"]
        }
      }
    },
    phpcs: {
      options: {
        standard: "Wordpress"
      },
      theme: {
        dir: ["../*.php", "../**/*.php"]
      },
      plugins: {
        dir: []
      }
    },
    phpunit: {
      options: {
        bootstrap: "../../../../tests/includes/bootstrap.php",
        colors: true
      },
      theme: {
        classes: {
          dir: ["../tests"]
        }
      },
      plugins: {
        classes: {
          dir: []
        }
      }
    },
    karma: {
      options: {
        browsers: ['PhantomJS'],
        singleRun: true
      },
      themeJS: {
        configFile: "../js/spec/karma.conf.js"
      },
      spaJS: {
        configFile: "../spa/spec/karma.conf.js"
      }
    },
    todo: {
      options: {
        marks: [
          {
            pattern: "TODO",
            color: "#F47605"
          }, {
            pattern: "FIXME",
            color: "red"
          }, {
            pattern: "NOTE",
            color: "blue"
          }
        ]
      },
      lessTODO: {
        src: ["../css/*.less", "../css/**/*.less"]
      },
      phpTODO: {
        src: ["../*.php", "../**/*.php"]
      },
      themeJSTODO: {
        src: ["../js/*.coffee", "../js/**/*.coffee"]
      },
      spaTODO: {
        src: ["../spa/*.coffee", "../spa/**/*.coffee"]
      }
    },
    less: {
      production: {
        options: {
          paths: ["../css"],
          cleancss: true,
          compress: true
        },
        files: [
          {
            expand: true,
            cwd: "../css",
            src: ["../css/*.styles.less"],
            dest: "../css",
            ext: ".styles.min.css"
          }
        ]
      }
    },
    clean: {
      prevBuilds: {
        src: ["../css/*.styles.min.css", "../js/src/*.scripts.min.js", "../spa/src/*.spa.min.js"],
        options: {
          force: true
        }
      },
      production: {
        src: ["../production/*"],
        options: {
          force: true
        }
      }
    },
    copyto: {
      production: {
        files: [
          {
            cwd: "../css",
            src: ["*.styles.min.css"],
            dest: "../production/"
          }, {
            cwd: "../js/src",
            src: ["*.scripts.min.js"],
            dest: "../production/"
          }, {
            cwd: "../spa/src",
            src: ["*.spa.min.js"],
            dest: "../production/"
          }
        ]
      }
    },
    notify: {
      readyToDeploy: {
        options: {
          title: "Code is ready to deploy"
        }
      }
    }
  });
  require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);
  grunt.registerTask("themeJSOptimize", "Optimize the theme JS files", function() {
    var files, subTasks;
    files = grunt.file.expand("../js/src/*.scripts.js");
    if (files.length === 0) {
      grunt.log.write("No files to optimize");
      return;
    }
    subTasks = getRequireJSTasks(files, "scripts");
    grunt.config.set('requirejs', subTasks);
    return grunt.task.run("requirejs");
  });
  grunt.registerTask("themespaOptimize", "Optimize the spa JS files", function() {
    var files, subTasks;
    files = grunt.file.expand("../spa/src/*.spa.js");
    if (files.length === 0) {
      grunt.log.write("No files to optimize");
      return;
    }
    subTasks = getRequireJSTasks(files, "spa");
    grunt.config.set('requirejs', subTasks);
    return grunt.task.run("requirejs");
  });
  grunt.registerTask("gitCommit", "Commit production files", function() {});
  getRequireJSTasks = function(files, pattern) {
    var folderPath, optimizedExtension, originalExtension, subTasks;
    subTasks = {};
    folderPath = pattern === 'scripts' ? 'js' : 'spa';
    originalExtension = "" + pattern + ".js";
    optimizedExtension = "" + pattern + ".min.js";
    files.map(function(file) {
      var config, name;
      file = file.replace("../" + folderPath + "/src/", "");
      config = {
        baseUrl: "../" + folderPath,
        mainConfigFile: "../" + folderPath + "/src/require.config.js",
        name: "src/bower_components/almond/almond",
        include: ["src/" + file],
        out: "../" + folderPath + "/src/" + (file.replace(originalExtension, optimizedExtension)),
        findNestedDependencies: true,
        optimize: 'none'
      };
      name = file.replace("." + pattern + ".js", "");
      subTasks[name] = {};
      return subTasks[name]["options"] = config;
    });
    return subTasks;
  };
  grunt.registerTask("compile", "Compile coffee file watcher", function(args) {
    return grunt.task.run("exec:" + args);
  });
  grunt.registerTask("validate", ["lesslint", "coffeelint", "jshint", "phpcs"]);
  grunt.registerTask("runtests", ["karma", "phpunit"]);
  grunt.registerTask("optimize", ["less", "themeJSOptimize", "themespaOptimize"]);
  grunt.registerTask("build", ["themeJSOptimize", "themespaOptimize", "less", "clean:production", "copyto", "clean:prevBuilds"]);
  return grunt.registerTask("deploy", ["validate", "runtests", "optimize", "clean", "copyto", "notify:readyToDeploy"]);
};
