// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['app', 'text!apps/apartment/templates/apartment.html'], function(App, memberTpl) {
  return App.module("Member.Views", function(Views, App) {
    var SingleView;
    SingleView = (function(_super) {
      __extends(SingleView, _super);

      function SingleView() {
        return SingleView.__super__.constructor.apply(this, arguments);
      }

      SingleView.prototype.tagName = 'tr';

      SingleView.prototype.className = 'user_class';

      SingleView.prototype.template = '<td class="v-align-middle width20 clickable"><div class="table_mob_hidden">Name</div>{{name}}</td> <td class="v-align-middle width20"><div class="table_mob_hidden">Date Joined</div>{{unitType}}</td> <td class="v-align-middle width20"><div class="table_mob_hidden">No Of Referrals</div>{{unitVariant}}</td> <td class="v-align-middle width20"><div class="table_mob_hidden">Points</div>{{building}}</td> <td class="v-align-middle width20 status"><div class="table_mob_hidden">Status</div>{{floor}}</td> <td class="v-align-middle width20"><div class="table_mob_hidden">Is a Customer</div>{{view}}</td> <td class="v-align-middle width20"><div class="table_mob_hidden">Is a Customer</div>{{status}}</td>';

      SingleView.prototype.events = {
        'click ': 'click'
      };

      SingleView.prototype.modelEvents = {
        'change:status': function() {
          return this.$el.find('.status').text(this.model.get("status"));
        }
      };

      SingleView.prototype.click = function() {
        return location.href = '#referrals/' + this.model.get('user_login') + '/' + this.model.get('ID');
      };

      SingleView.prototype.onShow = function() {
        return this.$el.find('.bolesemi').text(this.model.get("user_role"));
      };

      return SingleView;

    })(Marionette.ItemView);
    return Views.ProgramMember = (function(_super) {
      __extends(ProgramMember, _super);

      function ProgramMember() {
        return ProgramMember.__super__.constructor.apply(this, arguments);
      }

      ProgramMember.prototype.template = memberTpl;

      ProgramMember.prototype.className = '';

      ProgramMember.prototype.itemView = SingleView;

      ProgramMember.prototype.itemViewContainer = 'table#program-member-table tbody';

      ProgramMember.prototype.onShow = function() {
        return this.$el.find("#program-member-table").tablesorter({
          theme: 'blue',
          widthFixed: true,
          sortList: [[0, 1]],
          widgets: ['zebra', 'filter']
        }).tablesorterPager({
          container: $(".pager"),
          size: 25
        });
      };

      ProgramMember.prototype.events = {
        'click #submitform': function(e) {
          console.log('data');
          e.preventDefault();
          this.$el.find('#hideshow').addClass('collapsed');
          this.$el.find('#collapseOne').removeClass('collapse in');
          this.$el.find('#collapseOne').addClass('collapse');
          return this.trigger("filter:member:info", Backbone.Syphon.serialize(this));
        }
      };

      return ProgramMember;

    })(Marionette.CompositeView);
  });
});
