// Generated by CoffeeScript 1.7.1
define(['underscore', 'jasminejquery'], function(_) {
  return describe('apartment selectors filters', function() {
    var data, fixtures;
    fixtures = loadJSONFixtures('flats.json');
    alert(fixtures['flats.json']);
    data = fixtures['flats.json'];
    return it('must have 10 records', function() {
      return expect(_.size(data.flats)).toBe(10);
    });
  });
});
