// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['extm'], function(Extm) {
  var MainController, facing, facingnames, mainView, view, viewnames;
  view = [];
  facing = [];
  facingnames = [];
  viewnames = [];
  MainController = (function(_super) {
    __extends(MainController, _super);

    function MainController() {
      this._getView = __bind(this._getView, this);
      this.showRegionViews = __bind(this.showRegionViews, this);
      return MainController.__super__.constructor.apply(this, arguments);
    }

    MainController.prototype.initialize = function() {
      var layout;
      this.layout = layout = this._getView();
      App.layout = this.layout;
      this.listenTo(layout, 'show', this.showRegionViews);
      return this.show(layout);
    };

    MainController.prototype.showRegionViews = function() {
      var params;
      App.filter(params = {});
      msgbus.showApp('header').insideRegion(App.headerRegion).withOptions();
      return msgbus.showApp('screen:one').insideRegion(this.layout.screenOneRegion).withOptions();
    };

    MainController.prototype._getView = function() {
      return new mainView({
        templateHelpers: {
          SITEURL: SITEURL,
          VIEWS: VIEWS,
          FACINGS: FACINGS
        }
      });
    };

    return MainController;

  })(Extm.RegionController);
  mainView = (function(_super) {
    __extends(mainView, _super);

    function mainView() {
      return mainView.__super__.constructor.apply(this, arguments);
    }

    mainView.prototype.template = '<div id="notify" class="notifyBox" style="display:none;"> You have clicked on a box! </div> <div>dfsfsfs</div> <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right" id="cbp-spmenu-s2"> <h3>My Menu</h3> <ul> <li><a href="#"><span class="glyphicon glyphicon-heart"></span> Wishlist</a> <ul class="menuWishlist" id="showWishlist"> </ul> </li> <a href="#" id="compare" class="compareBtn">Compare</a> </ul> <div id="comparetext">Compare Apartments here! You can add Apartments to your wish list by clicking on the \'Add to wish list\' button on the view Apartment page after you have made a selection! You can compare up to 4 apartments!</div> </nav> <div id="screen-one-region" > </div> <div id="screen-two-region" > </div> <div id="screen-three-region" > </div> <div id="screen-four-region" > </div>';

    mainView.prototype.events = {
      'click .view': function(e) {
        var index, viewString;
        viewString = 'All';
        if ($('#' + e.target.id).prop('checked') === true) {
          view.push($('#' + e.target.id).val());
          viewnames.push($('#' + e.target.id).attr('data-name'));
        } else {
          console.log(index = view.indexOf($('#' + e.target.id).val()));
          if (index !== -1) {
            view.splice(index, 1);
            viewnames.splice(index, 1);
          }
        }
        if (view.length !== 0) {
          viewString = view.join(',');
        }
        App.defaults['view'] = viewString;
        $('#viewName').text(viewnames.join(','));
        return console.log(App.defaults);
      },
      'click .facing': function(e) {
        var facingString, index;
        facingString = 'All';
        console.log($('#' + e.target.id));
        if ($('#' + e.target.id).prop('checked') === true) {
          facing.push($('#' + e.target.id).val());
          facingnames.push($('#' + e.target.id).attr('data-name'));
        } else {
          console.log(index = facing.indexOf($('#' + e.target.id).val()));
          if (index !== -1) {
            facing.splice(index, 1);
            facingnames.splice(index, 1);
          }
        }
        if (facing.length !== 0) {
          facingString = facing.join(',');
        }
        App.defaults['facing'] = facingString;
        $('#facingName').text(facingnames.join(','));
        return console.log(App.defaults);
      },
      'click #compare': function(e) {
        var body, menuRight, menuTop, showRightPush, showTop, win;
        console.log($.cookie("key"));
        win = window.open(SITEURL + "/wishlist/#wishList", '_blank');
        win.focus();
        menuRight = document.getElementById("cbp-spmenu-s2");
        menuTop = document.getElementById("cbp-spmenu-s3");
        showTop = document.getElementById("showTop");
        showRightPush = document.getElementById("showRightPush");
        body = document.body;
        classie.toggle(showRightPush, "active");
        classie.toggle(body, "cbp-spmenu-push-toleft");
        return classie.toggle(menuRight, "cbp-spmenu-open");
      },
      'click .del': function(e) {
        var index, val;
        App.cookieArray = App.cookieArray;
        val = $('#' + e.target.id).attr('data-id');
        index = App.cookieArray.indexOf(parseInt(val));
        App.cookieArray.splice(index, 1);
        if (App.cookieArray.length <= 1) {
          $('#compare').hide();
        }
        $.cookie('key', App.cookieArray);
        localStorage.setItem("cookievalue", App.cookieArray);
        $('#errormsg').text("");
        return this.showWishList();
      },
      'click a': function(e) {
        return e.preventDefault();
      },
      'click .selectedunit': function(e) {
        var body, buildingModel, floorriserange, menuRight, menuTop, object, rangeArrayVal, rangeModel, showRightPush, showTop, unitModel;
        menuRight = document.getElementById("cbp-spmenu-s2");
        menuTop = document.getElementById("cbp-spmenu-s3");
        showTop = document.getElementById("showTop");
        showRightPush = document.getElementById("showRightPush");
        body = document.body;
        classie.toggle(showRightPush, "active");
        classie.toggle(body, "cbp-spmenu-push-toleft");
        classie.toggle(menuRight, "cbp-spmenu-open");
        App.unit['name'] = $('#' + e.target.id).attr('data-id');
        App.unit['flag'] = 1;
        unitModel = App.master.unit.findWhere({
          id: parseInt($('#' + e.target.id).attr('data-id'))
        });
        App.defaults['unitType'] = unitModel.get('unitType');
        App.defaults['building'] = unitModel.get('building');
        rangeModel = App.master.range;
        App.backFilter['screen3'].push("floor");
        App.backFilter['screen2'].push("floor", "unitVariant");
        buildingModel = App.master.building.findWhere({
          id: unitModel.get('building')
        });
        floorriserange = buildingModel.get('floorriserange');
        object = this;
        rangeArrayVal = [];
        $.each(floorriserange, function(index, value) {
          var end, i, start;
          rangeArrayVal = [];
          i = 0;
          start = parseInt(value.start);
          end = parseInt(value.end);
          while (parseInt(start) <= parseInt(end)) {
            rangeArrayVal[i] = start;
            start = parseInt(start) + 1;
            i++;
          }
          if (jQuery.inArray(parseInt(unitModel.get('floor')), rangeArrayVal) >= 0) {
            return App.defaults['floor'] = rangeArrayVal.join(',');
          }
        });
        App.navigate("screen-four");
        msgbus.showApp('header').insideRegion(App.headerRegion).withOptions();
        return msgbus.showApp('screen:four').insideRegion(App.layout.screenFourRegion).withOptions();
      }
    };

    mainView.prototype.regions = {
      screenOneRegion: '#screen-one-region',
      screenTwoRegion: '#screen-two-region',
      screenThreeRegion: '#screen-three-region',
      screenFourRegion: '#screen-four-region'
    };

    mainView.prototype.onShow = function() {
      var cookieOldValue, height;
      console.log(height = $(window).scrollTop());
      $(window).scroll(function() {
        height = $(window).scrollTop();
        if (height < 300) {
          $('.backBtn').addClass('hidden');
          return $('.slctnTxt').addClass('hidden');
        } else {
          $('.backBtn').removeClass('hidden');
          return $('.slctnTxt').removeClass('hidden');
        }
      });
      cookieOldValue = $.cookie("key");
      if (cookieOldValue === void 0 || $.cookie("key") === "") {
        cookieOldValue = [];
      } else {
        cookieOldValue = $.cookie("key").split(',').map(function(item) {
          return parseInt(item);
        });
      }
      if (cookieOldValue.length <= 1) {
        $('#compare').hide();
      }
      App.cookieArray = cookieOldValue;
      localStorage.setItem("cookievalue", App.cookieArray);
      return this.showWishList();
    };

    mainView.prototype.showWishList = function() {
      var building, element, model, selectedUnitsArray, table, unitType, unitVariant, _i, _len;
      table = "";
      if ($.cookie("key") !== void 0 && $.cookie("key") !== "") {
        console.log(selectedUnitsArray = $.cookie("key").split(","));
        table = "";
        for (_i = 0, _len = selectedUnitsArray.length; _i < _len; _i++) {
          element = selectedUnitsArray[_i];
          model = App.master.unit.findWhere({
            id: parseInt(element)
          });
          unitType = App.master.unit_type.findWhere({
            id: model.get('unitType')
          });
          unitVariant = App.master.unit_variant.findWhere({
            id: model.get('unitVariant')
          });
          building = App.master.building.findWhere({
            id: model.get('building')
          });
          table += '<li> <a href="#" id="unit' + element + '" data-id="' + element + '" class="selectedunit">' + model.get('name') + '</a> <a href="#" class="del" id="' + element + '" data-id="' + element + '"  ></a> <div class="clearfix"></div> </li>';
        }
      }
      console.log(table);
      return $('#showWishlist').html(table);
    };

    return mainView;

  })(Marionette.LayoutView);
  return msgbus.registerController('main:app', MainController);
});
