// Generated by CoffeeScript 1.7.1
define(['underscore', 'extm', 'async'], function(_, Extm, async) {
  return _.extend(Extm.Store.prototype, {
    getUnitTypes: function(available) {
      if (available == null) {
        available = true;
      }
    },
    getBuildingModel: function(buildingId) {}
  });
});
