// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['marionette'], function(Marionette) {
  var ApartmentSelector, RouterAPI;
  ApartmentSelector = (function(_super) {
    __extends(ApartmentSelector, _super);

    function ApartmentSelector() {
      return ApartmentSelector.__super__.constructor.apply(this, arguments);
    }

    ApartmentSelector.prototype.appRoutes = {
      'screen-three': 'showUnits',
      'screen-two': 'show',
      'screen-one/:params': 'showValues',
      'screen-two/:params': 'show',
      'screen-three/:params': 'showUnits',
      'screen-four/:params': 'showSelectedUnit'
    };

    return ApartmentSelector;

  })(Marionette.AppRouter);
  RouterAPI = {
    showValues: function(params) {
      if (params == null) {
        params = {};
      }
      App.filter(params);
      msgbus.showApp('header').insideRegion(App.headerRegion).withOptions();
      return msgbus.showApp('screen:one').insideRegion(App.mainRegion).withOptions();
    },
    show: function(params) {
      if (params == null) {
        params = {};
      }
      console.log('qqqqqqqqqqqqq');
      App.filter(params);
      msgbus.showApp('header').insideRegion(App.headerRegion).withOptions();
      return msgbus.showApp('screen:two').insideRegion(App.mainRegion).withOptions();
    },
    showUnits: function(params) {
      if (params == null) {
        params = {};
      }
      App.filter(params = {});
      msgbus.showApp('header').insideRegion(App.headerRegion).withOptions();
      return msgbus.showApp('screen:three').insideRegion(App.mainRegion).withOptions();
    },
    showSelectedUnit: function(unit, unittypeid, range, size) {
      msgbus.showApp('header').insideRegion(App.headerRegion).withOptions({
        unit: unit,
        unittypeid: unittypeid,
        range: range,
        size: size
      });
      return msgbus.showApp('screen:four').insideRegion(App.mainRegion).withOptions({
        unit: unit,
        unittypeid: unittypeid,
        range: range,
        size: size
      });
    }
  };
  return new ApartmentSelector({
    controller: RouterAPI
  });
});
