// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['marionette'], function(Marionette) {
  var ApartmentSelector, RouterAPI, staticApps;
  ApartmentSelector = (function(_super) {
    __extends(ApartmentSelector, _super);

    function ApartmentSelector() {
      return ApartmentSelector.__super__.constructor.apply(this, arguments);
    }

    ApartmentSelector.prototype.appRoutes = {
      'screen-two/unittype/:id/budget/:budget': 'show',
      'screen-three/unittype/:unitypeid/range/:range/building/:buildingid': 'showUnits',
      'screen-four/unit/:unit/unittype/:unittypeid/range/:range/size/:size': 'showSelectedUnit'
    };

    return ApartmentSelector;

  })(Marionette.AppRouter);
  staticApps = [];
  RouterAPI = {
    show: function(id, budget) {
      return msgbus.showApp('screen:two').insideRegion(App.mainRegion).withOptions({
        unittypeid: id
      });
    },
    showUnits: function(unitypeid, range, buildingid) {
      console.log(range);
      return msgbus.showApp('screen:three').insideRegion(App.mainRegion).withOptions({
        unitypeid: unitypeid,
        range: range,
        buildingid: buildingid
      });
    },
    showSelectedUnit: function(unit, unittypeid, range, size) {
      console.log("hiiiiiiiiiiiiiiiiii");
      return msgbus.showApp('screen:four').insideRegion(App.mainRegion).withOptions({
        unit: unit,
        unitypeid: unittypeid,
        range: range,
        size: size
      });
    }
  };
  return new ApartmentSelector({
    controller: RouterAPI
  });
});
